bdgt/frontend/dashboard/views.py
import logging

from flask import Blueprint, render_template


_log = logging.getLogger(__name__)

bp = Blueprint('dashboard', __name__)


@bp.route("/", methods=['GET'])
def index():
    return render_template("dashboard/index.html")

bdgt/frontend/transactions/views.py
import logging

from flask import Blueprint, flash, g, render_template, request, url_for
from sqlalchemy.sql.expression import not_

from bdgt import db
from bdgt.domain.models import Account, Category, Transaction


_log = logging.getLogger(__name__)

bp = Blueprint('transactions', __name__, url_prefix='/transactions')


@bp.route("/", methods=['GET'])
def list():
    query = Transaction.query

    q = request.args.get('q', '')
    if q != '':
        filters = q.split(' ')
        for f in filters:
            if ':' in f:
                exp = f.split(':')
                context = exp[0]
                stmt = exp[1]

                cpt = '=='
                if stmt[0] == '>':
                    if stmt[1] == '=':
                        cpt = '>='
                        stmt = stmt[2:]
                    else:
                        cpt = '>'
                        stmt = stmt[1:]
                elif stmt[0] == '<':
                    if stmt[1] == '=':
                        cpt = '<='
                        stmt = stmt[2:]
                    else:
                        cpt = '<'
                        stmt = stmt[1:]

                if context == "is":
                    if not hasattr(Transaction, stmt):
                        flash("{} is not a valid filter".format(f), 'warning')
                    else:
                        query = query.filter(getattr(Transaction, stmt))
                elif context == "not":
                    if not hasattr(Transaction, stmt):
                        flash("{} is not a valid filter".format(f), 'warning')
                    else:
                        query = query.filter(not_(getattr(Transaction, stmt)))
                elif context == "account":
                    query = query.join(Account).filter(Account.name == stmt)
                elif context == "amount":
                    query = query.filter(Transaction.amount.op(
                        cpt, is_comparison=True)(stmt))
                elif context == "date":
                    query = query.filter(Transaction.date.op(
                        cpt, is_comparison=True)(stmt))
                elif context == "category":
                    query = query.join(Category).filter(Category.name == stmt)
                else:
                    flash("{} is not a valid filter".format(f), 'warning')
            else:
                query = query.filter(Transaction.description.contains(f))

    page = int(request.args.get('page', 1))
    tx_pages = query.order_by(Transaction.date.desc()).paginate(page, 20)

    root_categories = Category.query.filter_by(parent_id=None).all()

    return render_template("transactions/index.html", tx_pages=tx_pages, q=q,
                           categories=root_categories)


@bp.route("/set_category", methods=['POST'])
def set_category():
    cat_id = request.json.get('cat_id')
    tx_ids = request.json.get('tx_ids')

    category = Category.query.get(cat_id)
    txs = Transaction.query.filter(Transaction.id.in_(tx_ids)).all()
    for tx in txs:
        tx.category = category
    db.session.commit()

    return "ok"


@bp.route("/set_reconciled", methods=['POST'])
def set_reconciled():
    reconciled = request.json.get('reconciled')
    tx_ids = request.json.get('tx_ids')

    txs = Transaction.query.filter(Transaction.id.in_(tx_ids)).all()
    for tx in txs:
        tx.reconciled = reconciled
    db.session.commit()

    return "ok"


@bp.route("/delete", methods=['POST'])
def delete():
    tx_ids = request.json.get('tx_ids')

    txs = Transaction.query.filter(Transaction.id.in_(tx_ids)).all()
    for tx in txs:
        db.session.delete(tx)
    db.session.commit()

    return "ok"


@bp.before_request
def before_request():
    g.section = 'transactions'


def url_for_page(page):
    args = request.args.copy()
    args['page'] = page
    return url_for(request.endpoint, **args)

bdgt/frontend/templates/_macros.html
{#
Renders field for bootstrap 3 standards.

Params:
  field - WTForm field
  kwargs - pass any arguments you want in order to put them into the html
           attributes.

  There are few exceptions: for - for_, class - class_, class__ - class_

Example usage:
  {{ macros.render_field(form.email, placeholder='Input email',
                         type='email') }}
#}
{% macro render_field(field, label_visible=true) -%}
  <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
    {% if (field.type != 'HiddenField' or
           field.type !='CSRFTokenField') and label_visible %}
      <label for="{{ field.id }}" class="control-label">
        {{ field.label }}
      </label>
    {% endif %}

    {{ field(class_='form-control', **kwargs) }}

    {% if field.errors %}
      {% for e in field.errors %}
        <p class="help-block">{{ e }}</p>
      {% endfor %}
    {% endif %}
  </div>
{%- endmacro %}


{#
Renders checkbox fields since they are represented differently in bootstrap

Params:
  field - WTForm field (there are no check, but you should put here only
          BooleanField.
  kwargs - pass any arguments you want in order to put them into the html
           attributes.

  There are few exceptions: for - for_, class - class_, class__ - class_

Example usage:
  {{ macros.render_checkbox_field(form.remember_me) }}
#}
{% macro render_checkbox_field(field) -%}
  <div class="checkbox">
    <label>
      {{ field(type='checkbox', **kwargs) }} {{ field.label }}
    </label>
  </div>
{%- endmacro %}


{#
Renders radio field

Params:
  field - WTForm field (there are no check, but you should put here only
          BooleanField.
  kwargs - pass any arguments you want in order to put them into the html
           attributes.

  There are few exceptions: for - for_, class - class_, class__ - class_

Example usage:
  {{ macros.render_radio_field(form.answers) }}
#}
{% macro render_radio_field(field) -%}
  {% for value, label, _ in field.iter_choices() %}
    <div class="radio">
      <label>
        <input type="radio" name="{{ field.id }}" id="{{ field.id }}"
               value="{{ value }}">
          {{ label }}
      </label>
    </div>
  {% endfor %}
{%- endmacro %}

{#
Renders date field

#}
{% macro render_date_field(field) -%}
  <div class='form-group'>
    <div class='input-group date' id='dtpicker-{{ field.id }}'>
          {{ field(class_='form-control', id=field.id, **kwargs) }}
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
    {% if field.errors %}
      {% for e in field.errors %}
        <p class="help-block">{{ e }}</p>
      {% endfor %}
    {% endif %}
  </div>
  <script type="text/javascript">
    $(function () {
      $('#dtpicker-{{ field.id }}').datetimepicker({
        pickTime: false
      });
    });
  </script>
{%- endmacro %}

{#
Renders file field
#}
{% macro render_file_field(field) -%}
  <div id="file_div" class="form-group">
    <div class="input-group">
      <span class="input-group-btn">
        <span class="btn btn-primary btn-file">
          Browse&hellip; {{ field(class='form-control', id=field.id, **kwargs) }}
        </span>
      </span>
      <input type="text" class="form-control" disabled>
    </div>
  </div>
{%- endmacro %}

{#
Renders WTForm in bootstrap way. There are two ways to call function:
  - as macros: it will render all field forms using cycle to iterate over
               them
  - as call: it will insert form fields as you specify:
     e.g. {% call macros.render_form(form, action_url=url_for('login_view'),
                                     action_text='Login',
                                     class_='login-form') %}
            {{ macros.render_field(form.email, placeholder='Input email',
                                   type='email') }}
            {{ macros.render_field(form.password,
                                   placeholder='Input password',
                                   type='password') }}
            {{ macros.render_checkbox_field(form.remember_me,
                                            type='checkbox') }}
          {% endcall %}

Params:
  form - WTForm class
  action_url - url where to submit this form
  action_text - text of submit button
  class_ - sets a class for form
#}
{% macro render_form(form, id_='', class_='', btn_class='btn btn-default') -%}
  <form method="POST" role="form" action="{{ action_url }}" id="{{ id_ }}"
        class="{{ class_ }}" enctype="{{ enctype }}">
    {{ form.hidden_tag() if form.hidden_tag }}
    {% if caller %}
      {{ caller() }}
    {% else %}
      {% for f in form %}
        {% if f.type == 'BooleanField' %}
          {{ render_checkbox_field(f) }}
        {% elif f.type == 'RadioField' %}
          {{ render_radio_field(f) }}
        {% elif f.type == 'HiddenField' or
                f.type == 'CSRFTokenField' %}
          {{ f }}
        {% elif f.type == 'DateField' or
                f.type == 'DateTimeField' %}
        {% elif f.type == 'FileField' %}
          {{ render_file_field(f) }}
        {% else %}
          {{ render_field(f) }}
        {% endif %}
      {% endfor %}
    {% endif %}
    <div class="form-group">
      <a class="btn btn-default" href="{{ url_for('dashboard.index') }}">
        Cancel
      </a>
      <button type="submit" class="btn btn-success">Save</button>
    </div>
  </form>
{%- endmacro %}

bdgt/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet"
          href="{{ url_for('static',
                           filename='libs/bootstrap/dist/css/bootstrap.min.css') }}">

    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/site.css') }}">

    {% block css %}
    {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Navbar header -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                                data-toggle="collapse"
                                data-target="#main_menu">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand logo"
              href="{{ url_for('dashboard.index') }}">
            <p>bdgt</p>
          </a>
        </div>
        <div class="collapse navbar-collapse" id="main_menu">
          <ul class="nav navbar-nav">
            <li class="{{ 'active' if g.section == 'accounts' }}">
              <a href="{{ url_for('accounts.index') }}">Accounts</a>
            </li>
            <li class="{{ 'active' if g.section == 'transactions' }}">
              <a href="{{ url_for('transactions.list') }}">Transactions</a>
            </li>
            <li class="{{ 'active' if g.section == 'categories' }}">
              <a href="{{ url_for('categories.index') }}">Categories</a>
            </li>
            <li class="{{ 'active' if g.section == 'imports' }}">
              <a href="{{ url_for('imports.form') }}">Import</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Flashed messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class="container-fluid">
          {% for category, message in messages %}
          <div class="alert alert-dismissable alert-{{ category if category else 'success'}}">
              <button type="button" class="close" data-dismiss="alert"
                      aria-hidden="true">&times;</button>
              <p>{{ message }}</p>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}

    <div class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>

    <script src="{{ url_for('static',
                            filename='libs/jquery/dist/jquery.min.js') }}">
    </script>
    <script src="{{ url_for('static',
                            filename='libs/bootstrap/dist/js/bootstrap.min.js') }}">
    </script>
    <script src="{{ url_for('static',
                            filename='libs/bootbox/bootbox.js') }}">
    </script>

    {% block js %}
    {% endblock %}
  </body>
</html>

bdgt/frontend/templates/form.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
  {% from "_macros.html" import render_form with context %}

  <div class="well">
    <h2>{{ form_title }}</h2>
    <div class="form-group">
      {{ render_form(form) }}
    </div>
  </div>
</div>

{% endblock %}

{% block js %}
<script>
   $(document).on('change', '.btn-file :file', function() {
     var input = $(this);
     numFiles = input.get(0).files ? input.get(0).files.length : 1;
     label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
     input.trigger('fileselect', [numFiles, label]);
   });

  $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
    var input = $(this).parents('.input-group').find(':text'),
    log = numFiles > 1 ? numFiles + ' files selected' : label;
    if( input.length ) {
      input.val(log);
    } else {
      if( log ) alert(log);
    }
  });
</script>
{% endblock %}