bdgt/frontend/categories/forms.py
from flask_wtf import Form
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.ext.sqlalchemy.orm import model_form

from bdgt.domain.models import Category


CategoryFormBase = model_form(Category, base_class=Form,
                              exclude=['parent', 'parent_id', 'subcategories',
                                       'transactions'])


class CategoryForm(CategoryFormBase):
    parent = QuerySelectField(query_factory=lambda: Category.query.all(),
                              allow_blank=True)

bdgt/frontend/categories/views.py
import logging

from flask import Blueprint, g, redirect, render_template, url_for


from bdgt import db
from bdgt.domain.models import Category
from bdgt.frontend.categories.forms import CategoryForm


_log = logging.getLogger(__name__)

bp = Blueprint('categories', __name__, url_prefix="/category")


@bp.route("/", methods=['GET'])
def index():
    root_categories = Category.query.filter_by(parent_id=None).all()
    return render_template("categories/index.html", categories=root_categories)


@bp.route("/new", methods=['GET', 'POST'])
@bp.route("/edit/<int:id>", methods=['GET', 'POST'])
def create_or_update(id=None):
    if id is None:
        title = "Add Category"
        category = Category()
    else:
        title = "Edit Category"
        category = Category.query.get(id)
    form = CategoryForm(obj=category)
    if form.validate_on_submit():
        form.populate_obj(category)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('categories.index'))
    return render_template('form.html', form=form, form_title=title,
                           action_url=url_for('categories.create_or_update',
                                              id=id))


@bp.route("/delete/<int:id>")
def delete(id):
    category = Category.query.get(id)
    db.session.delete(category)
    db.session.commit()
    return redirect(url_for('categories.index'))


@bp.before_request
def before_request():
    g.section = 'categories'

bdgt/frontend/templates/categories/index.html
{% extends "base.html" %}

{% macro render_category(category, level) -%}
<tr>
  <td style="vertical-align: middle;">
    <span style="margin-left: {{ level * 16 }}px;">
      {{ category.name }}
    </span>
  </td>
  <td>
    <div class="btn-group pull-right">
      <a class="btn btn-default btn-flat confirm"
         href="{{ url_for('categories.create_or_update', id=category.id) }}">
        <span class="glyphicon glyphicon-pencil"></span>
      </a>
      <a class="btn btn-default btn-flat confirm"
         href="{{ url_for('categories.delete', id=category.id) }}">
        <span class="glyphicon glyphicon-trash"></span>
      </a>
    </div>
  </td>
</tr>
{% if category.subcategories | length > 0 %}
  {% for subcategory in category.subcategories %}
    {{ render_category(subcategory, level + 1) }}
  {% endfor %}
{% endif %}
{%- endmacro %}

{% block content %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <a class="btn btn-primary"
         href="{{ url_for('categories.create_or_update') }}">
        New Category
      </a>
    </div>

    <table id="categories" class="table table-condensed">
      {% if categories | length > 0 %}
      <tbody>
        {% for category in categories %}
          {{ render_category(category, 0) }}
        {% endfor %}
      </tbody>
      {% else %}
        <p>No categories</p>
      {% endif %}
    </table>

  </div>
{% endblock %}

{% block js %}
{% endblock %}